# Generated by Django 5.2.5 on 2025-08-07 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jokesmodel',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 8, 7, 21, 3, 26, 735980, tzinfo=datetime.timezone.utc)),
        ),
    ]
