# Generated by Django 5.2.5 on 2025-08-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joking', '0002_alter_jokesmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jokesmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
